set nocompatible
filetype off
syntax enable
syntax on
call plug#begin('~/.vim/plugged')

Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'godlygeek/tabular'
Plug 'luochen1990/rainbow'
Plug 'plasticboy/vim-markdown'
Plug 'Raimondi/delimitMate'

call plug#end()

" Solarized Dark
" set background=dark
set t_Co=256
set t_Sb=^[[4%dm
set t_Sf=^[[3%dm]]]]
let g:solarized_termcolors=256
let g:solarized_termtrans=1
" let g:solarized_degrade=1
let g:solarized_visibility = 'high'
let g:solarized_contrast = 'high'
let g:solarized_hitrail = 1
" colorscheme solarized
colorscheme Tomorrow-Night-Eighties
let g:airline_theme='badwolf'
let g:airline_powerline_fonts=0
autocmd VimEnter * AirlineTheme solarized
" let g:airline#extensions#tabline#enabled=1


" Others
let g:rainbow_active = 1
set laststatus=2
highlight Normal ctermfg=grey ctermbg=black
set fileformats=unix,dos
set nowrap
set nobackup
set history=1000
set nu
set ai!
set ts=4
set sw=4
set ss=4
set expandtab
set autoindent
set cindent
set smartindent
set smarttab
set incsearch
set backspace=2
set pastetoggle=<f3>
au FileType python let b:delimitMate_nesting_quotes = ['"']
