# .bashrc
# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lm='ls -al|more'
alias tmux='tmux -2'
alias p='parallel'
alias pp='parallel --pipe -k'
# Source global definitions
if [ -f /etc/bashrc ]; then
- . /etc/bashrc
fi
export NVM_DIR="/opt/workplace/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
export PATH="/opt/workplace/rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PYENV_ROOT="/opt/workplace/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
eval "$(thefuck --alias)"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export GOROOT=/opt/go
export PATH="$GOROOT/bin:$PATH"
export GOPATH=/opt/workplace/goapp:/opt/workplace/elasticsearch-migration
export SCALA_HOME="/opt/scala-2.12.0"
export PATH="$PATH:$SCALA_HOME/bin"
export PATH="$PATH:/opt/workplace/sonar-scanner-2.8/bin"
